### PR TITLE
fix ASM for 32-bit Linux

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Review by mratsim — APPROVED** [review]
LGTM

rerunning the failed windows job (failed at decompression of some stuff).

**Comment by stefantalpalaru** [comment]
> (failed at decompression of some stuff)

It fails because those Mingw archive names were changed on the Nim site: https://nim-lang.org/install_windows.html

**Review by jlokier — COMMENTED** [review]
Is returning a mod 2^32 `int32` which is then sign-extended to `result: int64` really the right thing to do here?   That seems likely to break time calculations elsewhere during those moments when the TSC wraps around 2^31.  `rdtsc` returns a perfectly good 64-bit value in `EDX:EAX`, using the same expression as the 64-bit branch.

**Comment by stefantalpalaru** [comment]
The better fix can come in a new PR instead of blocking this one.

**Pull request merged**
